
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: nanowrimeter_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: nanowrimeter_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: nanowrimeter_production
  pool: 5
  username: 
  password: